package cn.n0texpecterr0r.timemovie.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.n0texpecterr0r.timemovie.location.bean.Location;
import cn.n0texpecterr0r.timemovie.saling.bean.SalingMovie;
import cn.n0texpecterr0r.timemovie.coming.bean.ComingMovie;

import cn.n0texpecterr0r.timemovie.db.LocationDao;
import cn.n0texpecterr0r.timemovie.db.SalingMovieDao;
import cn.n0texpecterr0r.timemovie.db.ComingMovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig salingMovieDaoConfig;
    private final DaoConfig comingMovieDaoConfig;

    private final LocationDao locationDao;
    private final SalingMovieDao salingMovieDao;
    private final ComingMovieDao comingMovieDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        salingMovieDaoConfig = daoConfigMap.get(SalingMovieDao.class).clone();
        salingMovieDaoConfig.initIdentityScope(type);

        comingMovieDaoConfig = daoConfigMap.get(ComingMovieDao.class).clone();
        comingMovieDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        salingMovieDao = new SalingMovieDao(salingMovieDaoConfig, this);
        comingMovieDao = new ComingMovieDao(comingMovieDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(SalingMovie.class, salingMovieDao);
        registerDao(ComingMovie.class, comingMovieDao);
    }
    
    public void clear() {
        locationDaoConfig.clearIdentityScope();
        salingMovieDaoConfig.clearIdentityScope();
        comingMovieDaoConfig.clearIdentityScope();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public SalingMovieDao getSalingMovieDao() {
        return salingMovieDao;
    }

    public ComingMovieDao getComingMovieDao() {
        return comingMovieDao;
    }

}
