package cn.n0texpecterr0r.timemovie.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.n0texpecterr0r.timemovie.location.bean.Location;

import cn.n0texpecterr0r.timemovie.db.LocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;

    private final LocationDao locationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);

        registerDao(Location.class, locationDao);
    }
    
    public void clear() {
        locationDaoConfig.clearIdentityScope();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

}
